# Generated by Django 4.2.9 on 2024-01-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='verification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField(unique=True)),
                ('passcode', models.CharField(max_length=255)),
            ],
        ),
    ]
