# Generated by Django 4.2.9 on 2024-01-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0002_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_room_id',
            field=models.IntegerField(default=0),
        ),
    ]
