# Generated by Django 4.2.9 on 2024-03-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0003_chat_chat_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_room_id',
            field=models.CharField(max_length=255),
        ),
    ]
