# Generated by Django 4.2.9 on 2024-03-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0004_alter_chat_chat_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='last_seen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField(unique=True)),
                ('last_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
