# Generated by Django 4.2.9 on 2024-03-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0005_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_seen',
            name='last_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
