# Generated by Django 4.2.9 on 2024-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0007_image_chat_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.IntegerField(unique=True)),
                ('report_message', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
