# Generated by Django 4.2.9 on 2024-05-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='images',
            field=models.ManyToManyField(null=True, to='Magic.image'),
        ),
    ]
