# Generated by Django 4.2.9 on 2024-05-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magic', '0009_alter_chat_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='images',
        ),
    ]
